from sqlalchemy.orm import Session
from .models import Chat, Message, User, MatchAnalysisReport
from .connection import engine
from typing import List, Dict, Any

def create_chat(report_id: str | None = None) -> str:
    """Create a new chat and return its UUID"""
    # Create a session - this is your "transaction" with the database
    session = Session(engine)

    try:
        # Create a new Chat instance (UUID auto-generated by default = uuid4)
        new_chat = Chat(report_id=report_id if report_id else None)

        # Add to session (stages it for saving)
        session.add(new_chat)
        
        # Commit writes it to the database
        session.commit()

        # Return the UUID as a string:
        return str(new_chat.id)
    
    finally:
        # Always close the session to free up database connections
        session.close()

def chat_exists(chat_id: str) -> bool:
    """Check if a chat exists by its UUID."""
    session = Session(engine)

    try:
        chat = session.query(Chat).filter_by(id=chat_id).first()
        return chat is not None
    finally:
        session.close()

def get_chat(chat_id: str) -> Dict[str, Any] | None:
    """Get chat by ID, including report_id."""
    session = Session(engine)
    
    try:
        chat = session.query(Chat).filter_by(id=chat_id).first()
        if not chat:
            return None
        
        return {
            "id": str(chat.id),
            "report_id": str(chat.report_id) if chat.report_id else None,
            "created_at": chat.created_at.isoformat()
        }
    finally:
        session.close()

def get_chats_by_report(report_id: str) -> List[Dict[str, Any]]:
    """Get all chats linked to a specific report, ordered by creation time (newest first)."""
    session = Session(engine)
    
    try:
        chats = session.query(Chat).filter_by(report_id=report_id).order_by(Chat.created_at.desc()).all()
        return [
            {
                "id": str(chat.id),
                "report_id": str(chat.report_id) if chat.report_id else None,
                "created_at": chat.created_at.isoformat()
            }
            for chat in chats
        ]
    finally:
        session.close()

def insert_message(chat_id: str, role: str, content: str, user_id: str | None = None) -> str:
    """Insert a message and return its UUID."""
    if role not in ('user', 'assistant', 'system'):
        raise ValueError(f"Invalid role: {role}. Must be 'user', 'assistant', or 'system'.")
    
    session = Session(engine)
    
    try:
        chat = session.query(Chat).filter_by(id=chat_id).first()
        if not chat:
            raise ValueError(f"Chat with id {chat_id} does not exist.")
        
        new_message = Message(
            chat_id=chat_id,
            role=role,
            content=content,
            user_id=user_id
        )
        
        session.add(new_message)
        session.commit()
        return str(new_message.id)
    finally:
        session.close()

def get_chat_messages(chat_id: str) -> List[Dict[str, Any]]:
    """Get all messages for a chat, ordered by creation time."""
    session = Session(engine)
    
    try:
        messages = session.query(Message).filter_by(chat_id=chat_id).order_by(Message.created_at.asc()).all()
        
        return [
            {
                "id": str(msg.id),
                "role": msg.role,
                "content": msg.content,
                "created_at": msg.created_at
            }
            for msg in messages
        ]
    finally:
        session.close()

def get_all_chat_ids() -> List[str]:
    """Get all chat IDs, ordered by creation time (newest first)."""
    session = Session(engine)
    
    try:
        chats = session.query(Chat).order_by(Chat.created_at.desc()).all()
        return [str(chat.id) for chat in chats]
    finally:
        session.close()

def get_all_chats() -> List[Dict[str, Any]]:
    """Get all chats with their metadata, ordered by creation time (newest first)."""
    session = Session(engine)
    
    try:
        chats = session.query(Chat).order_by(Chat.created_at.desc()).all()
        return [
            {
                "chat_id": str(chat.id),
                "created_at": chat.created_at.isoformat(),
                "report_id": str(chat.report_id) if chat.report_id else None
            }
            for chat in chats
        ]
    finally:
        session.close()

    
def get_user_by_api_key(api_key: str) -> Dict[str, Any] | None:
    """Get user by API key, returns None if not found."""
    session = Session(engine)
    
    try:
        user = session.query(User).filter_by(api_key=api_key).first()
        if not user:
            return None
        
        return {
            "id": str(user.id),
            "username": user.username
        }
    finally:
        session.close()


def create_match_analysis_report(team1: str, team2: str, game_date: str, content: str) -> str:
    """Create a match analysis report entry in the database and return its UUID.
    
    Args:
        team1: First team name
        team2: Second team name
        game_date: Game date in ISO format (YYYY-MM-DD)
        content: Report content
    """
    from datetime import datetime
    session = Session(engine)
    
    try:
        new_report = MatchAnalysisReport(
            team1=team1,
            team2=team2,
            game_date=datetime.fromisoformat(game_date),
            content=content
        )
        
        session.add(new_report)
        session.commit()
        return str(new_report.id)
    finally:
        session.close()


def get_match_analysis_report(report_id: str) -> Dict[str, Any] | None:
    """Get a match analysis report from the db by ID."""
    session = Session(engine)
    
    try:
        report = session.query(MatchAnalysisReport).filter_by(id=report_id).first()
        if not report:
            return None
        
        return {
            "id": str(report.id),
            "team1": report.team1,
            "team2": report.team2,
            "game_date": report.game_date.isoformat(),
            "content": report.content,
            "created_at": report.created_at.isoformat()
        }
    finally:
        session.close()

def get_all_match_analysis_reports() -> List[Dict[str, Any]]:
    """Get all match analysis reports from the db, ordered by creation time (newest first)."""
    session = Session(engine)
    
    try:
        reports = session.query(MatchAnalysisReport).order_by(MatchAnalysisReport.created_at.desc()).all()
        return [
            {
                "id": str(r.id),
                "team1": r.team1,
                "team2": r.team2,
                "game_date": r.game_date.isoformat(),
                "created_at": r.created_at.isoformat()
            }
            for r in reports
        ]
    finally:
        session.close()