from sqlalchemy.orm import Session
from .models import Chat, Message, User
from .connection import engine
from typing import List, Dict, Any

def create_chat() -> str:
    """Create a new chat and return its UUID"""
    # Create a session - this is your "transaction" with the database
    session = Session(engine)

    try:
        # Create a new Chat instance (UUID auto-generated by default = uuid4)
        new_chat = Chat()

        # Add to session (stages it for saving)
        session.add(new_chat)
        
        # Commit writes it to the database
        session.commit()

        # Return the UUID as a string:
        return str(new_chat.id)
    
    finally:
        # Always close the session to free up database connections
        session.close()

def chat_exists(chat_id: str) -> bool:
    """Check if a chat exists by its UUID."""
    session = Session(engine)

    try:
        chat = session.query(Chat).filter_by(id=chat_id).first()
        return chat is not None
    finally:
        session.close()

def insert_message(chat_id: str, role: str, content: str, user_id: str | None = None) -> str:
    """Insert a message and return its UUID."""
    if role not in ('user', 'assistant', 'system'):
        raise ValueError(f"Invalid role: {role}. Must be 'user', 'assistant', or 'system'.")
    
    session = Session(engine)
    
    try:
        chat = session.query(Chat).filter_by(id=chat_id).first()
        if not chat:
            raise ValueError(f"Chat with id {chat_id} does not exist.")
        
        new_message = Message(
            chat_id=chat_id,
            role=role,
            content=content,
            user_id=user_id
        )
        
        session.add(new_message)
        session.commit()
        return str(new_message.id)
    finally:
        session.close()

def get_chat_messages(chat_id: str) -> List[Dict[str, Any]]:
    """Get all messages for a chat, ordered by creation time."""
    session = Session(engine)
    
    try:
        messages = session.query(Message).filter_by(chat_id=chat_id).order_by(Message.created_at.asc()).all()
        
        return [
            {
                "id": str(msg.id),
                "role": msg.role,
                "content": msg.content,
                "created_at": msg.created_at
            }
            for msg in messages
        ]
    finally:
        session.close()

def get_all_chat_ids() -> List[str]:
    """Get all chat IDs, ordered by creation time (newest first)."""
    session = Session(engine)
    
    try:
        chats = session.query(Chat).order_by(Chat.created_at.desc()).all()
        return [str(chat.id) for chat in chats]
    finally:
        session.close()

    
def get_user_by_api_key(api_key: str) -> Dict[str, Any] | None:
    """Get user by API key, returns None if not found."""
    session = Session(engine)
    
    try:
        user = session.query(User).filter_by(api_key=api_key).first()
        if not user:
            return None
        
        return {
            "id": str(user.id),
            "username": user.username
        }
    finally:
        session.close()
